apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yd4pjw12c-python 
  janus-idp.io/tekton: yd4pjw12c-python
  backstage.io/kubernetes-id: yd4pjw12c-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yd4pjw12c-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml