apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yd4pjw12c-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:6e9edd66f5940ad18c245b661d88a404a6983ddd@sha256:d90198413b1fd53c7fa85ff6657ca1cf9f2d4db2a2c8032ba0b74621d80e3428
          name: container-image
